### ISSUE TITLE
Remove singleton data from cram files

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/nf-cmgg-test-datasets#4]
Remove all reads that have lost their pairs (singletons) from cram file, because they cause `CollectWGSmetrics` and CollectHSMetrics to fail 

@nvnieuwk , while you're editing the crams, can you do this too?

**Comment by nvnieuwk** [comment]
![](https://media.giphy.com/media/3o6MbaF4ZVj1Yqocjm/giphy.gif)

**Comment by nvnieuwk** [comment]
you're talking about `test.cram` and `test2.cram` right?

**Comment by matthdsm** [comment]
yep!
